from abc import ABC, abstractmethod
from typing import Tuple, Sequence, Self, Any
import os


class Tests(ABC):
    """
    Base class for all tests.

    The tests are responsible for testing the code generated by the coder.
    """
    def __init__(self, project_home: os.PathLike | None = None) -> None:
        """
        Initialize the tests.

        Args:
            project_home (os.PathLike | None, optional): The path to the project home. Defaults to None.
            test_files (Sequence[os.PathLike] | None, optional): The files that contain the tests. Defaults to None.
        """
        self.project_home = project_home

    def __add__(self, tests: Self | None) -> Self:
        """
        Add two tests together.

        Args:
            tests (Tests | None): The tests to add to these tests.

        Returns:
            Tests: The combined tests.
        """
        if tests is None:
            return self

        return self.combine(tests)

    @abstractmethod
    def combine(self, tests: Self) -> Self:
        """
        Combine another set of tests with these tests.

        Args:
            tests (Tests): The tests to combine with these tests.

        Returns:
            Tests: The combined tests.
        """
    
    @abstractmethod
    def test_files(self) -> Sequence[os.PathLike]:
        """
        Get the files that contain the tests.

        Returns:
            Sequence[os.PathLike]: The files that contain the tests.
        """
    
    @abstractmethod
    def run(self) -> Tuple[bool, Any]:
        """
        Run the tests.

        Returns:
            Tuple[bool, Any]: Whether the tests passed and the test results.
        """


class NoTests(Tests):
    """
    A set of tests that does not contain any tests.
    """
    def combine(self, tests: Tests) -> Tests:
        """
        Combine another set of tests with these tests.

        Args:
            tests (Tests): The tests to combine with these tests.

        Returns:
            Tests: The combined tests.
        """
        return tests

    def test_files(self) -> Sequence[os.PathLike]:
        """
        Get the files that contain the tests.

        Returns:
            Sequence[os.PathLike]: The files that contain the tests.
        """
        return []

    def run(self) -> Tuple[bool, Any]:
        """
        Run the tests.

        Returns:
            Tuple[bool, Any]: Whether the tests passed and the test results.
        """
        return True, ""
