from abc import ABC, abstractmethod
from typing import Tuple, Self, Any, Iterable
import os


class Tests(ABC):
    """
    Base class for all tests.

    The tests are responsible for testing the code generated by the coder.
    """
    def __init__(self, project_home: os.PathLike | None = None) -> None:
        """
        Initialize the tests.

        Args:
            project_home (os.PathLike | None, optional): The path to the project home. Defaults to None.
        """
        self.project_home = project_home

    def __add__(self, tests: Self | None) -> Self:
        """
        Add two tests together.

        Args:
            tests (Tests | None): The tests to add to these tests.

        Returns:
            Tests: The combined tests.
        """
        if tests is None:
            return self

        return self._combine(tests)

    @abstractmethod
    def _combine(self, tests: Self) -> Self:
        """
        Combine another set of tests with these tests.

        Args:
            tests (Tests): The tests to combine with these tests.

        Returns:
            Tests: The combined tests.
        """
    
    @abstractmethod
    def test_files(self) -> Iterable[os.PathLike]:
        """
        Get the files that contain the all the tests.

        Returns:
            Iterable[os.PathLike]: The files that contain the tests.
        """
    
    def run(self) -> Tuple[bool, Any]:
        """
        Run the tests.

        Returns:
            Tuple[bool, Any]: Whether the tests passed and the test results.
        """

        if len(self.test_files()) == 0:
            return False, ""
        
        return self._run()
    
    @abstractmethod
    def _run(self) -> Tuple[bool, Any]:
        """
        Run the tests.

        Returns:
            Tuple[bool, Any]: Whether the tests passed and the test results.
        """


class NoTests(Tests):
    """
    A set of tests that does not contain any tests.
    """
    def _combine(self, tests: Tests) -> Tests:
        return tests

    def test_files(self) -> Iterable[os.PathLike]:
        return []

    def _run(self) -> Tuple[bool, Any]:
        return False, ""
